// Generated by Dagger (https://dagger.dev).
package com.example.accenturechallenge.data.network.pokemonapi.mapper;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ApiMapperImpl_Factory implements Factory<ApiMapperImpl> {
  @Override
  public ApiMapperImpl get() {
    return newInstance();
  }

  public static ApiMapperImpl_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static ApiMapperImpl newInstance() {
    return new ApiMapperImpl();
  }

  private static final class InstanceHolder {
    private static final ApiMapperImpl_Factory INSTANCE = new ApiMapperImpl_Factory();
  }
}
